org: anmolsudhir
app: lambda-backend
service: lambda-service
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    MONGO_URL: ${env:MONGO_URL}
    AWS_S3_ACCESS_KEY: ${env:AWS_S3_ACCESS_KEY}
    AWS_S3_SECRET_KEY: ${env:AWS_S3_SECRET_KEY}

functions:
  auth:
    handler: functions/auth/src/index.handler
    events:
      - httpApi:
          method: GET
          path: /auth/health
      - httpApi:
          method: POST
          path: /auth/signin/guest
      - httpApi:
          method: GET
          path: /auth/session-verify
          
  video:
    handler: functions/video/src/index.handler
    events:
      - httpApi:
          method: GET
          path: /video/health
      - httpApi:
          method: POST
          path: /video/upload
  
  party:
    handler: functions/party/src/index.handler
    events:
      - httpApi:
          method: GET
          path: /party/health
      - httpApi:
          method: POST
          path: /party/create
      - httpApi:
          method: GET
          path: /party/{id}
      - httpApi:
          method: DELETE
          path: /party/{id}

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
