name: Serverless CI/CD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      AWS_SERVERLESS_ARN: ${{ secrets.AWS_SERVERLESS_ARN }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }} # Required for logging into serverless

    steps:
      - uses: actions/checkout@v3

      # Setup nodejs 20.x
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install serverless framework
      - name: Install Serverless Framework
        run: npm install -g serverless

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Clean install the dependencies
      - name: Installing Dependencies
        run: pnpm install --frozen-lockfile

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-south-1
          role-to-assume: ${{ env.AWS_SERVERLESS_ARN }}
          role-session-name: GitHubActions # Session name

      # Deploy serverless service
      - name: Deploy to AWS
        run: serverless deploy
